<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BriefFiniteElement.Net" Version="2.0.5" />
    <PackageReference Include="PicoGK" Version="2.0.0-beta11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Picocnc.csproj" />
  </ItemGroup>

</Project>
